name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Pull Docker images
      run: docker-compose pull

    - name: Start services
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: sleep 5  # or longer, depending on your services

    - name: Run tests
      run: |
        cd frontend
        npm install
        npm test

    - name: Run backend tests
      run: |
        cd backend
        npm install
        npm test

    - name: Stop services
      run: docker-compose down
